### ISSUE TITLE
Insert a node at a specific position in a linked list #Week 7 Problem

### ISSUE THREAD

**Issue by spardha-codinggirl** [20sw084/3-Months-Preparation-Kit-HackerRank#103]
Hi @20sw084 , I want to solve the problem 
https://www.hackerrank.com/challenges/three-month-preparation-kit-insert-a-node-at-a-specific-position-in-a-linked-list/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=three-month-preparation-kit&playlist_slugs%5B%5D=three-month-week-seven
Please assign this issue to me.

**Comment by shaffayqazi** [comment]
Assign it to me.
