### ISSUE TITLE
Separate the numbers

### ISSUE THREAD

**Issue by 20sw084** [20sw084/3-Months-Preparation-Kit-HackerRank#14]
https://www.hackerrank.com/challenges/three-month-preparation-kit-separate-the-numbers/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=three-month-preparation-kit&playlist_slugs%5B%5D=three-month-week-four
Bring the Solution of this Problem and upload it in Week 4 Folder.

**Comment by manaswini-ks** [comment]
Hey @20sw084, could you please assign this issue to me?
I can get started with working on it

**Comment by manaswini-ks** [comment]
@20sw084 , I had a query.
I can submit it in either C++ or Java, what is preferred?

**Comment by 20sw084** [comment]
Both are allowed.
