### ISSUE TITLE
Gaming Array 1

### ISSUE THREAD

**Issue by 20sw084** [20sw084/3-Months-Preparation-Kit-HackerRank#26]
https://www.hackerrank.com/challenges/three-month-preparation-kit-an-interesting-game-1/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=three-month-preparation-kit&playlist_slugs%5B%5D=three-month-week-six
Bring the Solution of this Problem and upload it in Week 6 Folder.

**Comment by 05hiteshbansal** [comment]
hey @20sw084 can you assign me this issue
