### ISSUE TITLE
Forming a Magic Square

### ISSUE THREAD

**Issue by 20sw084** [20sw084/3-Months-Preparation-Kit-HackerRank#27]
https://www.hackerrank.com/challenges/three-month-preparation-kit-magic-square-forming/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=three-month-preparation-kit&playlist_slugs%5B%5D=three-month-week-six
Bring the Solution of this Problem and upload it in Week 6 Folder.

**Comment by Abhishek-03113** [comment]
hey @20sw084 Can you assign this issue to me ?

**Comment by akadeepesh** [comment]
Let me solve this @20sw084

**Comment by yashita89** [comment]
hey would like to contribute pls assign me with this

**Comment by shaffayqazi** [comment]
Assign it to me.
