### ISSUE TITLE
New Year Chaos

### ISSUE THREAD

**Issue by 20sw084** [20sw084/3-Months-Preparation-Kit-HackerRank#39]
https://www.hackerrank.com/challenges/three-month-preparation-kit-new-year-chaos/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=three-month-preparation-kit&playlist_slugs%5B%5D=three-month-week-seven
Bring the Solution of this Problem and upload it in Week 7 Folder.

**Comment by JoelChandanshiv** [comment]
Hi @20sw084 can you please assign me this issue .
