### ISSUE TITLE
Sherlock and the Valid String

### ISSUE THREAD

**Issue by 20sw084** [20sw084/3-Months-Preparation-Kit-HackerRank#41]
https://www.hackerrank.com/challenges/three-month-preparation-kit-sherlock-and-valid-string/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=three-month-preparation-kit&playlist_slugs%5B%5D=three-month-week-seven
Bring the Solution of this Problem and upload it in Week 7 Folder.

**Comment by JoelChandanshiv** [comment]
Hi @20sw084 can u please assign me this issue .
