### ISSUE TITLE
Add Two Numbers

### ISSUE THREAD

**Issue by talha-ansarii** [20sw084/3-Months-Preparation-Kit-HackerRank#60]
https://leetcode.com/problems/add-two-numbers/ i want to solve this leetcode problem\
@20sw084 please assign me this issue

**Comment by talha-ansarii** [comment]
@20sw084 under hacktoberfest

**Comment by roniskywalker** [comment]
Hello [20sw084](https://github.com/20sw084), I have added 2. Add Two Numbers problem's solution. Please do check.
