### ISSUE TITLE
Balanced Brackets Problem

### ISSUE THREAD

**Issue by spardha-codinggirl** [20sw084/3-Months-Preparation-Kit-HackerRank#93]
Hi @20sw084 , I want to solve this problem https://www.hackerrank.com/challenges/three-month-preparation-kit-balanced-brackets/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=three-month-preparation-kit&playlist_slugs%5B%5D=three-month-week-eight. Please assign this issue to me.

**Comment by spardha-codinggirl** [comment]
Hi @20sw084 , I have resolved this issue. PR - #96

**Comment by 20sw084** [comment]
> Hi @20sw084 , I have resolved this issue. PR - #96

alright, Thanks.
