### ISSUE TITLE
Diagonal Traversal of a 2-D matrix

### ISSUE THREAD

**Issue by RichaBanerjee** [20sw084/3-Months-Preparation-Kit-HackerRank#94]
Hello @20sw084 ! I would like to solve Diagonal Traversal of a 2-D matrix problem on LeetCode.
Can you please assign it to me?

**Comment by 20sw084** [comment]
> Hello @20sw084 ! I would like to solve Diagonal Traversal of a 2-D matrix problem on LeetCode. Can you please assign it to me?

Sure

**Comment by tanay-nagde** [comment]
Hello @20sw084 ! I would like to solve Diagonal Traversal of a 2-D matrix problem on LeetCode. Can you please assign it to me?

**Comment by RichaBanerjee** [comment]
> > Hello @20sw084 ! I would like to solve Diagonal Traversal of a 2-D matrix problem on LeetCode. Can you please assign it to me?
> 
> Sure

Thanks!!

**Comment by 20sw084** [comment]
> tanay

Hey, Please create separate issue for that.

**Comment by tanay-nagde** [comment]
okay
